apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: 448049823362.dkr.ecr.ap-south-1.amazonaws.com/myrepo:8
      imagePullSecrets:
        - name: ecr-registry
